spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: root
# mybatis-plus
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: cn.chenjinzhao.blog.pojo.po
# JWT相关
jwt:
  # 过期时间(分钟)
  expiration: 10
  # 私钥
  secret: "%#$WS%@TW^1"
  tokenHeader: Authorization
  tokenHead: "Token:"